/**
 * 统一节点数据模型。
 *
 * 整个项目的核心抽象是这一句：**所有上游订阅先被解析成 `ProxyNode`，所有客户端格式
 * 再从 `ProxyNode` 生成**。解析器有 N 个、生成器有 M 个，但两侧只需各自面对这一个模型，
 * 而不是 N×M 种两两转换。
 *
 * `ProxyNode` 是**判别联合**（discriminated union），以 `type` 字段区分。这不是为了好看：
 * 各协议的字段差异极大（trojan 用 password、vmess 用 uuid+alterId、ssr 还多两层混淆参数），
 * 用一个"字段全都可选"的大对象来装，编译器就再也帮不上忙了——把 trojan 的密码当成
 * vmess 的 UUID 读出来，这类错误只会在用户导入配置失败时才被发现。
 *
 * 本文件属于 core 纯函数层：只有类型与常量，没有任何 IO。
 */

// ─────────────────────────────────────────────────────────────
//  协议与传输层
// ─────────────────────────────────────────────────────────────

/** v1 支持解析的代理协议。新增协议时同步更新 {@link PROXY_TYPES}。 */
export type ProxyType = 'vmess' | 'vless' | 'trojan' | 'ss' | 'ssr' | 'hysteria2' | 'tuic';

/** 运行时可枚举的协议列表（类型层面的 `ProxyType` 无法在运行时遍历）。 */
export const PROXY_TYPES: readonly ProxyType[] = [
  'vmess',
  'vless',
  'trojan',
  'ss',
  'ssr',
  'hysteria2',
  'tuic',
] as const;

export function isProxyType(v: string): v is ProxyType {
  return (PROXY_TYPES as readonly string[]).includes(v);
}

/**
 * 传输层。
 *
 * 注意 `h2` 与 `http` 是两回事：`h2` 指 HTTP/2 传输（Clash 写作 `h2`），
 * `http` 指伪装成 HTTP/1.1 的 TCP 传输（Clash 写作 `network: http`）。
 * 上游订阅里两者常被混用，解析时需要按来源格式区分。
 */
export type Network = 'tcp' | 'ws' | 'grpc' | 'h2' | 'http' | 'quic';

export interface WsOptions {
  path?: string;
  /** 常见的只有 Host 一项，但协议允许任意头，故用 Record。 */
  headers?: Record<string, string>;
  /** WebSocket 早期数据（0-RTT）。Clash.Meta 的 `max-early-data`。 */
  maxEarlyData?: number;
  earlyDataHeaderName?: string;
}

export interface GrpcOptions {
  serviceName?: string;
  /** `gun` 为单路复用，`multi` 为多路。省略时按客户端默认值处理。 */
  mode?: 'gun' | 'multi';
}

export interface H2Options {
  path?: string;
  host?: string[];
}

export interface HttpOptions {
  method?: string;
  path?: string[];
  headers?: Record<string, string[]>;
}

/**
 * 传输层配置。
 *
 * 之所以把各传输的选项分开成 `ws` / `grpc` / `h2` / `http` 子对象而不是平铺，
 * 是因为不同传输的 `path` 语义并不相同（ws 的 path 是字符串，http 的 path 是字符串数组），
 * 平铺会导致字段互相污染。
 */
export interface Transport {
  network: Network;
  ws?: WsOptions;
  grpc?: GrpcOptions;
  h2?: H2Options;
  http?: HttpOptions;
}

/** REALITY 参数。只有 VLESS 会用到。 */
export interface RealityOptions {
  /** 服务端公钥（URI 里的 `pbk`）。 */
  publicKey: string;
  /** 短 ID（URI 里的 `sid`）。可为空字符串，含义与缺省不同，故保留空串。 */
  shortId?: string;
  /** 爬虫路径（URI 里的 `spx`），实际很少用到。 */
  spiderX?: string;
}

export interface TlsOptions {
  enabled: boolean;
  /** SNI / servername。缺省时客户端一般回落到 server 字段。 */
  sni?: string;
  alpn?: string[];
  /** uTLS 指纹，如 `chrome` / `firefox` / `safari`。Clash.Meta 的 `client-fingerprint`。 */
  fingerprint?: string;
  /** 证书指纹固定（Clash.Meta 的 `fingerprint`），与上面的 uTLS 指纹是两个东西。 */
  certFingerprint?: string;
  /** 跳过证书校验。默认 false —— 静默放行自签证书是安全问题，必须由订阅显式声明。 */
  allowInsecure?: boolean;
  reality?: RealityOptions;
}

/** Shadowsocks 插件（obfs / v2ray-plugin / shadow-tls 等）。 */
export interface PluginOptions {
  name: string;
  /** 插件参数原样保留。不同插件的参数集完全不同，不做归一化。 */
  opts: Record<string, string | number | boolean>;
}

// ─────────────────────────────────────────────────────────────
//  节点
// ─────────────────────────────────────────────────────────────

/**
 * 节点的来源与推导信息。
 *
 * 这些字段**不参与指纹计算**——它们描述"这个节点是从哪来的、我们怎么看它"，
 * 而不是"连上去需要什么"。同一台服务器出现在两个订阅里应当被识别为同一节点。
 */
export interface NodeMeta {
  /** ISO 3166-1 alpha-2 地区码（如 `HK` / `JP` / `GB`），由 region.ts 推断，可能推断不出。 */
  region?: string;
  /** 所属订阅源 id。 */
  sourceId: string;
  /** 所属订阅源显示名，供 UI 与重命名模板使用。 */
  sourceName: string;
  /** 自由标签，供过滤规则匹配。v1 由解析器写入少量自动标签（如 `reality`）。 */
  tags: string[];
}

/** Link metadata for a node generated by the chain expansion pass. */
export interface ChainLink {
  /** Final display name of the entry node. */
  viaName: string;
  /** Stable fingerprint of the entry node. */
  viaFingerprint: string;
}

/**
 * Link metadata for a node whose dial address was swapped for an IX relay entry.
 *
 * 存在的第一理由是**幂等**：改写 pass 跑第二遍时 `server` 已经是入口地址，
 * 于是会把 `tls.sni` 补成入口域名 —— 得到一个"看起来配全了、实际必然握手失败"
 * 的节点，比不改写危险得多，而且没有任何测试会自然发现它。有了这个标记，
 * 第二遍能直接认出"已经改过"并跳过。
 *
 * 附带收益：界面能显示「经 xx 中转」，`originServer` 让排障能查回原落地地址。
 */
export interface IxLink {
  /** 中转入口主机名 —— 客户端实际拨号的地址，已过 `normalizeHost`。 */
  entryHost: string;
  /** 中转入口端口，由中转平台分配。 */
  entryPort: number;
  /** 改写前的 server。排障时靠它查回真正的落地机。 */
  originServer: string;
  /** 改写前的 port。 */
  originPort: number;
}

interface BaseNode {
  /**
   * 稳定指纹，见 fingerprint.ts。
   *
   * 用作节点主键：去重靠它，"手动勾选节点"的持久化也靠它。
   * 关键性质是**节点改名不会改变指纹**——上游订阅每 12 小时刷新一次，
   * 机场随时可能把 `🇭🇰 HK-01` 改成 `🇭🇰 香港01`，如果用名字做主键，
   * 用户勾选的节点会在第一次刷新后全部失效。
   */
  fingerprint: string;
  /** 显示名，来自上游，可能被重命名规则改写。 */
  name: string;
  server: string;
  /** 1–65535。解析器负责校验范围。 */
  port: number;
  /** 是否支持 UDP 转发。上游未声明时为 undefined，由生成器决定默认值。 */
  udp?: boolean;
  meta: NodeMeta;
  /** Set only by core/chain.ts; parsers never accept upstream chain fields. */
  chain?: ChainLink;
  /** Set only by core/ix.ts; parsers never accept upstream ix fields. */
  ix?: IxLink;
}

export interface VmessNode extends BaseNode {
  type: 'vmess';
  uuid: string;
  /**
   * AlterID。现代 VMess（AEAD）恒为 0。
   * 非 0 值意味着旧版 MD5 认证，部分新客户端已不再支持，生成器需要如实传递。
   */
  alterId: number;
  /** `auto` / `aes-128-gcm` / `chacha20-poly1305` / `none` 等。 */
  cipher: string;
  transport: Transport;
  tls?: TlsOptions;
}

export interface VlessNode extends BaseNode {
  type: 'vless';
  uuid: string;
  /** XTLS 流控，如 `xtls-rprx-vision`。空值表示不启用。 */
  flow?: string;
  /** VLESS 的 encryption 目前恒为 `none`，保留字段是为了将来协议扩展。 */
  encryption?: string;
  transport: Transport;
  tls?: TlsOptions;
}

export interface TrojanNode extends BaseNode {
  type: 'trojan';
  password: string;
  transport: Transport;
  /** Trojan 本身以 TLS 为前提，故此处不可选。 */
  tls: TlsOptions;
}

export interface SsNode extends BaseNode {
  type: 'ss';
  cipher: string;
  password: string;
  plugin?: PluginOptions;
}

export interface SsrNode extends BaseNode {
  type: 'ssr';
  cipher: string;
  password: string;
  /** 协议插件，如 `auth_aes128_md5`。 */
  protocol: string;
  protocolParam?: string;
  /** 混淆插件，如 `tls1.2_ticket_auth`。 */
  obfs: string;
  obfsParam?: string;
}

export interface Hysteria2Node extends BaseNode {
  type: 'hysteria2';
  password: string;
  /** 混淆类型，目前只有 `salamander`。 */
  obfs?: string;
  obfsPassword?: string;
  /** 上下行带宽声明，如 `100 mbps`。Hysteria 的拥塞控制依赖它。 */
  up?: string;
  down?: string;
  tls: TlsOptions;
}

export interface TuicNode extends BaseNode {
  type: 'tuic';
  uuid: string;
  password: string;
  /** `cubic` / `bbr` / `new_reno`。 */
  congestionController?: string;
  /** `native` / `quic`。 */
  udpRelayMode?: string;
  tls: TlsOptions;
}

/** 统一节点模型。以 `type` 判别。 */
export type ProxyNode =
  | VmessNode
  | VlessNode
  | TrojanNode
  | SsNode
  | SsrNode
  | Hysteria2Node
  | TuicNode;

/**
 * 解析器的产出：尚未计算指纹、尚未绑定来源的"半成品"节点。
 *
 * 存在的理由是先有鸡还是先有蛋：指纹由节点内容算出，所以解析器不可能在构造节点时
 * 就填好它；而来源信息（sourceId / sourceName）只有调用方知道。
 * 由 {@link finalizeNode} 统一补齐这两部分。
 *
 * 这里用**分配式条件类型**逐个成员做 Omit。直接写 `Omit<ProxyNode, ...>` 是不行的：
 * `Omit` 内部用 `keyof`，而联合类型的 `keyof` 是各成员键的**交集**，
 * 结果会退化成只剩公共字段（name/server/port/type）的对象，
 * uuid、password 这些协议字段全部消失，判别联合也就失效了。
 */
type DistributiveDraft<T> = T extends unknown ? Omit<T, 'fingerprint' | 'meta'> : never;

export type ProxyNodeDraft = DistributiveDraft<ProxyNode>;

// ─────────────────────────────────────────────────────────────
//  解析结果
// ─────────────────────────────────────────────────────────────

/**
 * 单条解析失败的记录。
 *
 * 解析上游订阅时**不能因为一个坏节点就整体失败**——机场经常在订阅里混入格式错误的行，
 * 或者使用我们尚未支持的协议。正确做法是跳过它、记下来、继续解析其余节点，
 * 最后把失败清单如实呈现给用户。静默吞掉会让用户以为节点数变少是服务商的问题。
 */
export interface ParseIssue {
  /** 出问题的原始内容，会被截断以免日志爆炸。 */
  raw: string;
  reason: string;
}

export interface ParseResult {
  nodes: ProxyNodeDraft[];
  issues: ParseIssue[];
}

// ─────────────────────────────────────────────────────────────
//  流量信息
// ─────────────────────────────────────────────────────────────

/**
 * `Subscription-Userinfo` 响应头承载的流量信息。
 *
 * 这是机场订阅事实上的标准（无 RFC），形如：
 * `upload=96701335; download=143028274; total=161061273600; expire=1803225600`
 *
 * 四个字段都可能缺失：不限量套餐没有 `total`，长期套餐没有 `expire`。
 * 因此除了 upload/download 之外都是可选的。
 */
export interface TrafficInfo {
  /** 已上传字节数。 */
  upload: number;
  /** 已下载字节数。 */
  download: number;
  /** 总配额字节数。缺失表示不限量。 */
  total?: number;
  /** 到期时间，Unix 秒（注意不是毫秒）。缺失表示不过期。 */
  expire?: number;
}
